####################################################################################
# Docker-compose file for spinning up a twitter-extract container
# USAGE: docker-compose up -d
#
####################################################################################

version: '3.2'

services:
  twitter-extract:
    container_name: twitter-extract
    hostname: twitter-extract
    build:
      context: .
      dockerfile: Dockerfile
    image: twitter-extract:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "127.0.0.1:9229:9229" # Node debugging port
